Measurment api guide
kartoza/tomorrownow_gap pull request #131
Opened 2024-09-05 05:30 UTC by ketankartoza

This PR is for the issue #129

2024-09-05 07:11 UTC, mvmaltitz reviewed
I have made some changes to the wording. We should add the data and attribute tables.

2024-09-06 12:33 UTC, mvmaltitz reviewed
This looks good

2024-09-10 11:15 UTC, danangmassandy requested changes

2024-09-10 11:15 UTC, danangmassandy commented on docs/src/developer/api/guide/measurment.md
> +![Python code to access API](./img/api-guide-8.png)
@ketankartoza, can you use the code block instead of image here? so the user can copy paste the codes. It would also be good to have another language example like using curl.

2024-09-10 11:15 UTC, danangmassandy commented on docs/src/developer/api/guide/measurment.md
> +Click on the GET API it will show the attribute to enter to get the data. Click on the 1️⃣ `Try it out` button, to fill the detailed in the 2️⃣ available fields. After filling the details click on th
there is typo on 'Exicute' button

2024-09-10 11:15 UTC, danangmassandy commented on docs/src/developer/api/guide/measurment.md
> +| **WIP** |
please remove the WIP and attributes under the section

2024-09-10 11:18 UTC, danangmassandy commented
@ketankartoza can you also add another section called available format types?
The API can have different output types:

- json: this type is only available for querying by single point
- csv
- netcdf: Only available for historical_reanalysis and seasonal_forecast.

2024-09-12 06:27 UTC, ketankartoza commented on docs/src/developer/api/guide/measurment.md
> +![Python code to access API](./img/api-guide-8.png)
Okay @danangmassandy I will add 2-3 examples.

2024-09-12 11:25 UTC, danangmassandy approved these changes
Looks good, thanks @ketankartoza!

2024-09-12 11:25 UTC, merged