Add split polygon to bbox script
kartoza/tomorrownow_gap pull request #92
Opened 2024-08-13 04:46 UTC by meomancer

This will fix https://github.com/kartoza/tomorrownow_gap/issues/65

2024-08-14 05:08 UTC, danangmassandy requested changes

2024-08-14 05:08 UTC, danangmassandy commented on django_project/gap/factories/preferences.py
> +        lambda: Polygon([
@meomancer can you please change the default polygon to below? this one is proposed by Phillip.
Proposed BB:
Lat: -27deg S to +16deg N
Long: 21.8 deg E to 52 deg E

2024-08-14 05:10 UTC, danangmassandy requested changes

2024-08-14 05:10 UTC, danangmassandy commented on django_project/gap/models/preferences.py
> +    area_of_interest = models.PolygonField(
can we set default of area of interest to below? This bbox is from Phillip.
Proposed BB:
Lat: -27deg S to +16deg N
Long: 21.8 deg E to 52 deg E

2024-08-22 05:57 UTC, meomancer commented
Hi @danangmassandy default is added
![Selection_140](https://github.com/user-attachments/assets/da055054-8a72-479b-a8d7-c47bfb960098)

2024-08-22 06:02 UTC, danangmassandy approved these changes
Thanks @meomancer

2024-08-22 06:02 UTC, merged